# Generated by Django 3.2.5 on 2021-08-02 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='camp_name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='conducted_by',
        ),
        migrations.AddField(
            model_name='gallery',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
