# Generated by Django 3.2.5 on 2021-08-03 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210802_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimage',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
