# Generated by Django 3.2.5 on 2021-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
