# Generated by Django 3.2.5 on 2021-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wimage',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='wimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='wimage',
            name='image',
            field=models.ImageField(upload_to='postimages/'),
        ),
    ]
