# Generated by Django 3.2.5 on 2021-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210814_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=123, null=True)),
                ('no', models.CharField(blank=True, max_length=123, null=True)),
                ('message', models.CharField(blank=True, max_length=123, null=True)),
            ],
        ),
    ]
