# Generated by Django 3.2.5 on 2021-08-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210815_0531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emailer',
            new_name='Email',
        ),
    ]
