# Generated by Django 3.2.5 on 2021-08-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_emailer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
