# Generated by Django 3.2.5 on 2021-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, null=True),
        ),
    ]
