# Generated by Django 3.2.5 on 2021-08-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizzes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
