# Generated by Django 3.2.5 on 2021-08-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
    ]
